name: cherrys_ledger
description: "Cherry's Ledger"
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  # export deps (later we will use)
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  excel: ^4.0.6

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: NotoSansMyanmar
      fonts:
        - asset: assets/fonts/NotoSansMyanmar-Regular.ttf
