name: cherrys_ledger
description: Cherryâ€™s Ledger
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  excel: ^4.0.6

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: NotoSansMyanmar
        - asset: assets/fonts/NotoSansMyanmar-Regular.ttf

dev_dependencies:
  flutter_lints: ^6.0.0
